spring.application.name=anidromvost
spring.datasource.url=jdbc:postgresql://localhost:5432/anidromvost
spring.datasource.username=postgres
spring.datasource.password=deltaq123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.expired=6666669

spring.jpa.hibernate.ddl-auto=create-drop